USE [master]
GO

/****** Object:  Database [EasyDb]    Script Date: 17/05/2017 13:53:02 ******/
CREATE DATABASE [EasyDb] ON  PRIMARY 
( NAME = N'EasyDb', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL.1\MSSQL\DATA\EasyDb.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'EasyDb_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL.1\MSSQL\DATA\EasyDb_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

--ALTER DATABASE [EasyDb] SET COMPATIBILITY_LEVEL = 90
--GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EasyDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [EasyDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [EasyDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [EasyDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [EasyDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [EasyDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [EasyDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [EasyDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [EasyDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [EasyDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [EasyDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [EasyDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [EasyDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [EasyDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [EasyDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [EasyDb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [EasyDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [EasyDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [EasyDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [EasyDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [EasyDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [EasyDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [EasyDb] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [EasyDb] SET  MULTI_USER 
GO

ALTER DATABASE [EasyDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [EasyDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [EasyDb] SET  READ_WRITE 
GO


